version: '2'

volumes:
  data_volume:

services:
  db:
    image: mysql
    # image: postgres
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: volunteer_planner
      MYSQL_USER: vp
      MYSQL_PASSWORD: volunteer_planner

      # POSTGRES_DB: volunteer_planner
      # POSTGRES_USER: vp
      # POSTGRES_PASSWORD: volunteer_planner
    volumes:
      - data_volume:/var/lib/mysql
    hostname: db
    mem_limit: 1G
    memswap_limit: 2G
    #cpuset: "0"

  web:
    build: .
    entrypoint: ["/usr/local/bin/python", "manage.py"]
    command: ["runserver", "0.0.0.0:8000"]
    volumes:
      - .:/opt/vpcode
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: "volunteer_planner.settings.docker_mysql"
      # DJANGO_SETTINGS_MODULE: "volunteer_planner.settings.docker_postgres"
    hostname: web
    mem_limit: 1G
    memswap_limit: 2G
    #cpuset: "1"
